
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake-4.1.1-windows-x86_64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "E:/cmake-4.1.1-windows-x86_64/share/cmake-4.1/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "E:/mingw64/mingw64/bin/"
      - "E:/fzf/bin/"
      - "E:/cmake-4.1.1-windows-x86_64/bin/"
      - "E:/vcpkg/"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/"
    searched_directories:
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/ninja-build.com"
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/ninja-build.exe"
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/ninja-build"
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/ninja.com"
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/ninja.exe"
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/ninja"
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/samu.com"
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/samu.exe"
      - "D:/Flutter/flutter/bin/cache/dart-sdk/bin/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu"
      - "E:/mingw64/mingw64/bin/ninja-build.com"
      - "E:/mingw64/mingw64/bin/ninja-build.exe"
      - "E:/mingw64/mingw64/bin/ninja-build"
      - "E:/mingw64/mingw64/bin/ninja.com"
      - "E:/mingw64/mingw64/bin/ninja.exe"
      - "E:/mingw64/mingw64/bin/ninja"
      - "E:/mingw64/mingw64/bin/samu.com"
      - "E:/mingw64/mingw64/bin/samu.exe"
      - "E:/mingw64/mingw64/bin/samu"
      - "E:/fzf/bin/ninja-build.com"
      - "E:/fzf/bin/ninja-build.exe"
      - "E:/fzf/bin/ninja-build"
      - "E:/fzf/bin/ninja.com"
      - "E:/fzf/bin/ninja.exe"
      - "E:/fzf/bin/ninja"
      - "E:/fzf/bin/samu.com"
      - "E:/fzf/bin/samu.exe"
      - "E:/fzf/bin/samu"
      - "E:/cmake-4.1.1-windows-x86_64/bin/ninja-build.com"
      - "E:/cmake-4.1.1-windows-x86_64/bin/ninja-build.exe"
      - "E:/cmake-4.1.1-windows-x86_64/bin/ninja-build"
      - "E:/cmake-4.1.1-windows-x86_64/bin/ninja.com"
      - "E:/cmake-4.1.1-windows-x86_64/bin/ninja.exe"
      - "E:/cmake-4.1.1-windows-x86_64/bin/ninja"
      - "E:/cmake-4.1.1-windows-x86_64/bin/samu.com"
      - "E:/cmake-4.1.1-windows-x86_64/bin/samu.exe"
      - "E:/cmake-4.1.1-windows-x86_64/bin/samu"
      - "E:/vcpkg/ninja-build.com"
      - "E:/vcpkg/ninja-build.exe"
      - "E:/vcpkg/ninja-build"
      - "E:/vcpkg/ninja.com"
      - "E:/vcpkg/ninja.exe"
      - "E:/vcpkg/ninja"
      - "E:/vcpkg/samu.com"
      - "E:/vcpkg/samu.exe"
      - "E:/vcpkg/samu"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/ninja-build.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/ninja-build.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/ninja-build"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/ninja.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/ninja.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/ninja"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/samu.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/samu.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/Scripts/samu"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/ninja-build.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/ninja-build.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/ninja-build"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/ninja.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/ninja.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/ninja"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/samu.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/samu.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Python312/samu"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/ninja-build.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/ninja-build.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/ninja-build"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/ninja.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/ninja.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/ninja"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/samu.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/samu.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Python/Launcher/samu"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/ninja.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/ninja.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/ninja"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/samu.com"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/samu.exe"
      - "C:/Users/Dong Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "D:\\Flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "E:\\mingw64\\mingw64\\bin\\"
        - "E:\\fzf\\bin\\"
        - "E:\\cmake-4.1.1-windows-x86_64\\bin\\"
        - "E:\\vcpkg\\"
        - "C:\\Users\\Dong Nguyen\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\"
        - "C:\\Users\\Dong Nguyen\\AppData\\Local\\Programs\\Python\\Python312\\"
        - "C:\\Users\\Dong Nguyen\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\Dong Nguyen\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Dong Nguyen\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "E:\\mingw64\\mingw64\\bin\\"
...
